### ISSUE TITLE
Feedback button should go to a simple feedback form

### ISSUE THREAD

**Issue by eoinnoble** [creativecommons/open-ledger#103]
Probably not hooked up yet, but the blue feedback button doesn't currently do anything.

**Comment by lizadaly** [comment]
Yup, follow-on work from #74

**Comment by lizadaly** [comment]
Per Ryan, this can just be a Google form with a few questions:

* Did you like this? [y/n] (TBD wording)
* Was this useful? [y/n]
* How could it be better? [open text]

* Would you like to hear from us again? If so, give us your email: [open text]

**Comment by lizadaly** [comment]
The button has been linked to a Google Form, but needs copy/approval from @ryanmerkley

**Comment by lizadaly** [comment]
This was done.
