### ISSUE TITLE
Suggested lists need an opaque background

### ISSUE THREAD

**Issue by eoinnoble** [creativecommons/open-ledger#104]
When adding a photo to an existing list, suggested list names need a non-transparent background by default, like they do when you hover over them.

![screen shot 2016-12-12 at 12 30 34](https://cloud.githubusercontent.com/assets/3576438/21101258/270be998-c070-11e6-9f93-9b70875c20ae.png)

**Comment by lizadaly** [comment]
They sure do. Done.
