### ISSUE TITLE
Filters are broken?

### ISSUE THREAD

**Issue by eoinnoble** [creativecommons/open-ledger#111]
When I used them on my searches the filters didn’t seem to do anything. Maybe adding a result count would make this easier to discern, but excluding cultural works still returned non-photo results (though maybe that’s a tagging issue) when searching for 'penguin'.

**Comment by lizadaly** [comment]
All that toggle does is filter by content provider, so you should see only results from Flickr and 500px with 'photographs' on, but only Rijksmuseum and NYPL with 'cultural works' on. Maybe the language should be more like "return results from photography sites or cultural institutions"?

**Comment by lizadaly** [comment]
I've changed the language to make this more clear.
