### ISSUE TITLE
Adding a photo to a list from search results should leave you on that page

### ISSUE THREAD

**Issue by eoinnoble** [creativecommons/open-ledger#114]
When adding a photo to a list from the search results page, _clicking_ on a suggested list name takes you to the page for the photo you're trying to add to the list. Users would probably prefer to stay on the search results page. If you add the photo to the list using your keyboard then you get what I assume would be the desired behaviour.

**Comment by lizadaly** [comment]
That's just a bug, the event handler for the image is getting in the way. It's supposed to work the way you described and I didn't notice the regression because I usually use the keyboard.

**Comment by lizadaly** [comment]
This experience should be improved now.
