### ISSUE TITLE
Linking to creator on image results preview 

### ISSUE THREAD

**Issue by janeatcc** [creativecommons/open-ledger#127]
More of a question. Should we link directly to creator's pages in on the image results page when you put your cursor over an image? before you can go directly to the image? Did we do this for attribution reasons?

**Comment by lizadaly** [comment]
The author's name is hyperlinked and it does go directly to their image, assuming we have a creator link in the first place. We only do for Flickr and 500px results, not NYPL/Rijks.

<img width="209" alt="open_ledger_prototype" src="https://cloud.githubusercontent.com/assets/19571/21610617/14c987f8-d197-11e6-9e76-0d0e8b21792f.png">

**Comment by janeatcc** [comment]
Right, so I'm wondering if we should do this from the results page. Do we have an incentive to keep people on our search pages? If so, then we should probably not link directly from results page, even if we show the author handle.

**Comment by lizadaly** [comment]
I see! Well, that's up to you guys. Happy to do whatever you prefer.

**Comment by janeatcc** [comment]
Cool. cc: @ryanmerkley & @robmyers

**Comment by robmyers** [comment]
Our ideal attribution does link to both the work and the author:

https://wiki.creativecommons.org/wiki/Best_practices_for_attribution#This_is_an_ideal_attribution

although the RDFa+HTML from the chooser only links the name to the creator's page (click on "This part is optional... and add a name and url):

https://creativecommons.org/choose/#metadata

So the attribution here is correct when attributing the work.

These are thumbnails, though. I'd ask legal about what we are required to do for thumbnails (I seem to remember a ruling from a few years back about image thumbnails...).

In any case I think it's good karma to have the names linked here as it makes sense from a best-attribution-practice point of view (we are after all displaying and attributing the image). But I do see how it could intercept the user's selection of the image.

This may be something that it's worth taking to wider testing and seeing how people get on with it.

**Comment by janeatcc** [comment]
Agree @robmyers, to take it to further user testing.

**Comment by lizadaly** [comment]
I removed the link to the author in search results as it wasn't adding value but did complicate the UI, particularly on mobile. The link to the author (if available) still exists on the image detail page.
