### ISSUE TITLE
Change URL to ccsearch.creativecommons.org

### ISSUE THREAD

**Issue by lizadaly** [creativecommons/open-ledger#129]
The name of the app is changing from Open Ledger to Creative Commons Search. @ryanmerkley would like to use ccsearch.creativecommons.org as the domain name.

Please add the DNS entries for:

ccsearch
ccsearch-dev 

and get new certs for both (we may have to do that cert validation dance again with AWS? Not sure.)

When those are in place, please have openledger* 301 redirect to the new names.

I'll update the copy on the website and the github repo to match.

**Comment by robmyers** [comment]
I've added them to the dns, pointing at the openledger servers on EBS (the same as for the openledger dns).

I've requested the certificates and, yes, it looks like you'll have to check the email again. PM me in slack if you need anything doing for this, I'm out for the rest of the week but I'll keep this moving.

**Comment by lizadaly** [comment]
OK, I did the certificate request dance from the AWS CLI that I did last time for both ccsearch and ccsearch-dev

**Comment by robmyers** [comment]
Confusingly, there are now two ccsearch / ccsearch-dev certificate requests in Amazon, all four showing as "pending validation". I'm going to delete them and put in new requests. Please keep an eye out for the emails again, I'm sorry about this.

**Comment by lizadaly** [comment]
This is now working, last step will be force-redirecting openledger* to ccsearch.

**Comment by robmyers** [comment]
The redirects are now in place.
