### ISSUE TITLE
Pingdom account perms

### ISSUE THREAD

**Issue by lizadaly** [creativecommons/open-ledger#133]
I did get an invite to Pingdom and created an account, but it was just for me (giving me 1 basic check). I don't seem to have any ability to modify checks under the CC account itself. This is what my CC dashboard looks like:

![image](https://cloud.githubusercontent.com/assets/19571/21773603/be188550-d65d-11e6-9c69-e5f6a447d983.png)

Whereas when I switch to my personal account, I get many more options:

![image](https://cloud.githubusercontent.com/assets/19571/21773620/cd9afb48-d65d-11e6-9377-dbfcd5575634.png)

I think my role under the CC account needs to be modified to give me the ability to add checks.

**Comment by robmyers** [comment]
Try now? The documentation doesn't match up with what I'm seeing on the site, but I've made you an Admin in the place I could find to make someone an Admin of some sort.

**Comment by lizadaly** [comment]
I have admin on "Beepmanager", which is a sub-product? Something? But not access to "Monitoring", which is what I'd need to actually... monitor things. Sorry this is confusing!

![image](https://cloud.githubusercontent.com/assets/19571/21779993/eb494842-d677-11e6-9e9f-f93c007475ef.png)

**Comment by robmyers** [comment]
Just talking to Pingdom.

**Comment by robmyers** [comment]
You should now be an actual, factual Admin.

I've a support ticket submitted regarding some billing weirdness, hopefully that won't interrupt our service but I'll let you know if there are any problems.

**Comment by lizadaly** [comment]
Looks great now, thank you for tracking that down!
