### ISSUE TITLE
Add basic profanity/offensive term filter to List data

### ISSUE THREAD

**Issue by lizadaly** [creativecommons/open-ledger#135]
List descriptions and titles are user-generated content that can be made public. Ensure that basic precautions are taken to prevent obvious profanity or harmful terms from being included in these fields.

**Comment by lizadaly** [comment]
@robmyers Do you have a word blacklist already in use on the blog/wiki?

**Comment by robmyers** [comment]
No word list, we're just using Akismet. Which might be an idea, there's a Python library for the API.

**Comment by lizadaly** [comment]
Can you send me the Akismet auth creds out-of-band?

**Comment by lizadaly** [comment]
Implemented both Akismet (spam) and https://github.com/dariusk/wordfilter for word list filtering. Note that the word list filter may include many false positives; we can tune if it is too restrictive.
