### ISSUE TITLE
fix typo in explanation on About CC Search page

### ISSUE THREAD

**Issue by sarahpearson** [creativecommons/open-ledger#138]
I noticed this sentence has a typo: 

Creative Commons’ “CC Search” project will develop and release an open online search and re-use tool that will allow high-quality content from the commons to surface more seamless and accessible. 

Maybe "more seamlessly and accessibly" or "in a more seamless and accessible way" ?

**Comment by lizadaly** [comment]
Changed to "in a more seamless and accessible way", though this was @ryanmerkley's text so please reopen if you'd like something different.
