### ISSUE TITLE
language to add to footer for CC Search

### ISSUE THREAD

**Issue by sarahpearson** [creativecommons/open-ledger#140]
Can you please add the bolded language below? (bolded only so you can see what is new)

This is a prototype of the CC Search, aggregating data from publicly available repositories of open content. **It is made publicly available for testing and discussion purposes only. Please report bugs or other problems in our Github repository (LINK). Note that Creative Commons is not hosting the images, so you should contact the original repository to have any infringing content removed.**

**Comment by lizadaly** [comment]
Done!
