### ISSUE TITLE
When there are a lot of words over an image it's hard to know where to click

### ISSUE THREAD

**Issue by little-wow** [creativecommons/open-ledger#157]
<img width="219" alt="screen shot 2017-02-06 at 1 27 51 pm" src="https://cloud.githubusercontent.com/assets/7093838/22660746/b9715738-ec70-11e6-8450-c83bbd706ba8.png">

In an example like this, it's hard to know where to click because there are a lot of words and it looks like all you can do is click on the words.

**Comment by mmoreshead** [comment]
Came here to log this issue too!

**Comment by lizadaly** [comment]
Fix would be to make long titles abbreviate more aggressively, and/or disable showing the creator in search results (as suggested by #127) which would also reduce the amount of text in a result.

**Comment by little-wow** [comment]
Is there a way to make the words hyperlinked? I kept trying to click on the words thinking they would be a hyperlink

**Comment by lizadaly** [comment]
I couldn't get that to work while still keeping the creator links hyperlinked, which might be another argument against keeping those links.

**Comment by lizadaly** [comment]
I made some design changes here to tighten things up: 

![image](https://cloud.githubusercontent.com/assets/19571/22895000/f1c64b20-f1e8-11e6-9111-18c443dbc823.png)

* Smaller font size
* Truncates title more aggressively
* Changed 'Title by Creator' to 'Title, Creator' (to save 3 characters)
* Removed the hyperlink to creator 
* Made the text link to the image detail
* Left-aligned the credit (looks better in cases where the image is narrow or it was line-breaking at just one or two words)

There are still a few hyperlink dead spots in the result overlay that might be nice to clean up in the future, but this should be an improvement.
