### ISSUE TITLE
IE11

### ISSUE THREAD

**Issue by robmyers** [creativecommons/open-ledger#160]
A user has reported that search is not working on IE11.

I tested in IE11 on Windows 8 and did have problems -

![image](https://cloud.githubusercontent.com/assets/21746/22712564/352a0950-ed53-11e6-8557-b4990cd354b9.png)

The console shows the following for this search:

![image](https://cloud.githubusercontent.com/assets/21746/22712614/71f3cc90-ed53-11e6-8c93-5e3c5fa0b521.png)

**_IE13 and 14 on Windows 10 didn't have this problem._**

IE11 on All platforms tested (Windows 7, 8, 8.1) did have this problem.

IE 10 on Windows 7 had the problem. The error log is:

![image](https://cloud.githubusercontent.com/assets/21746/22713025/d61f20ce-ed54-11e6-939b-1edd87b7468e.png)

IE 9 on Windows 7 had the problem until I cleared the cache, when it then looked like this:

![image](https://cloud.githubusercontent.com/assets/21746/22712816/3008c488-ed54-11e6-8b9b-c1232503ce8c.png)

(so, single column.)

The error log for the problem is:

![image](https://cloud.githubusercontent.com/assets/21746/22713153/49a22cda-ed55-11e6-8380-9367896aa26e.png)

IE8 doesn't render well and doesn't show results:

![image](https://cloud.githubusercontent.com/assets/21746/22713245/a0e57cf4-ed55-11e6-845d-78234ddbacbe.png)

 The log for this is:

![image](https://cloud.githubusercontent.com/assets/21746/22713224/8b14215a-ed55-11e6-8b3b-1d4530e9cf69.png)

**Comment by lizadaly** [comment]
We should only support IE 11 and up; MS itself does not [support 10 or below](http://venturebeat.com/2016/01/12/microsoft-ends-support-for-ie8-ie9-ie10-and-windows-8/).

It looks like the bug is in grid.js (which may be the underlying masonry plugin that does the image layout). If a fix isn't trivial, we could simply bypass the masonry layout and fall back to a rigid grid for IE.

**Comment by robmyers** [comment]
Not supporting unsupported browsers makes sense. :-)

**Comment by mmoreshead** [comment]
Another report from a user: 

 	Trying CC for the first time. I search for 'Caravaggio' at Metropolitan Museum of Art and get response '8 images' and now see 'Next' and 'Prev' on the screen, but no images. There is some momentary activity when I hit Next/Prev but no image appears.
Using Windows 10.

**Comment by robmyers** [comment]
@mmoreshead Do we know which version of IE they are using? I assume 11 or earlier but any details are helpful. :-)

**Comment by mmoreshead** [comment]
this one is 10, it's in my note up there, easy to miss though.

**Comment by robmyers** [comment]
It says Windows 10? If it's IE 10 on Windows that makes sense. :-)

**Comment by lizadaly** [comment]
IE 11 and Edge should now work.
