### ISSUE TITLE
Reduce the size of the space above search results

### ISSUE THREAD

**Issue by lizadaly** [creativecommons/open-ledger#176]
In user testing as well as in user feedback, there are complaints that search results begin too far down the page:

> After a search, allow me to reduce the amount of white space above the images. On my Desktop browser, 1/3 of the returned images are 'below the fold', so a lot of extra page-downing. Currently, after a search, the top half of the browser window is the search bar and filters.

**Comment by pa-w** [comment]
The PR #191 has been merged so I am closing this issue
