### ISSUE TITLE
Frequent error messages when clicking on Europeana images in search results

### ISSUE THREAD

**Issue by DavidHaskiya** [creativecommons/open-ledger#185]
When clicking on Europeana search results I get frequent error messages ("Oops! That page can’t be found.
That page may no longer exist, or you may need to be logged in to see it."), dev console tells me it's a HTTP404. 

The issue is not consistent. 

Example of Europeana object that fails, https://ccsearch.creativecommons.org/image/detail/TFVi2MOHYtwVqMWd09KZAw==

Example of Europeana object that works, 
https://ccsearch.creativecommons.org/image/detail/NPKqFBz-vne_e5xfd2eb2g==

**Comment by lizadaly** [comment]
A search query that exhibits the behavior:

https://ccsearch.creativecommons.org/?search=Rembrandt&page=1&search_fields=title&search_fields=creator&search_fields=tags&per_page=20&providers=europeana

Result 1 is in the search engine and the database. 
Result 2 is in the search engine and not the database.

**Comment by lizadaly** [comment]
The database and the search engine are now in sync. The search query above should only return results that we actually have.

The record noted in the original ticket is still missing—that is not a bug! The bug was that its stale entry was still in the search engine.
