### ISSUE TITLE
Issue with "Can I filters" for Europeana content?

### ISSUE THREAD

**Issue by DavidHaskiya** [creativecommons/open-ledger#186]
When I search for Rembrandt in Europeana and with no filters set for how I can use the content I get results: https://ccsearch.creativecommons.org/?search=rembrandt&page=1&search_fields=title&search_fields=creator&search_fields=tags&per_page=50&work_types=cultural&providers=europeana

When I set that I want to use commercially or adapt/modify I get no results:
https://ccsearch.creativecommons.org/?search=rembrandt&page=1&licenses=ALL-%24&licenses=ALL-MOD&search_fields=title&search_fields=creator&search_fields=tags&per_page=50&work_types=cultural&providers=europeana

Which is strange because, if you go back to the first search result link, a lot of the returned objects are Public Domain marked meaning they should be commercially reusable and allowed to modify and adapt.

**Comment by lizadaly** [comment]
There was an error in how the license data was stored. This has been corrected.
