### ISSUE TITLE
Upgrade to Django 2.0

### ISSUE THREAD

**Issue by pa-w** [creativecommons/open-ledger#212]
Currently we require 1.8 but this should be changed so we have django 2.0 + python 3.6

- [x] django_cas_ng only supports 1.x so we need to find a replacement for it

**Comment by pa-w** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Backend - Upgrade platform](https://trello.com/c/F7za812M/5-backend-upgrade-platform)

**Comment by aldenstpage** [comment]
In production now
