### ISSUE TITLE
Create a mechanism to "copy the attribution for this photo"

### ISSUE THREAD

**Issue by lizadaly** [creativecommons/open-ledger#23]
This feature should be available from [#22].

Start with the human-readable deed and loop @sarahpearson in to review.

**Comment by robmyers** [comment]
I've taken a few passes at this with Garmonbozia, the XMP/Exif work we did and currently the WordPress plugin. The only thing I'd say on the technical side is to watch out for uneven support for the clipboard on different platforms.

**Comment by lizadaly** [comment]
Yep, some browsers historically needed Flash for this. https://clipboardjs.com looks pretty good (uses a modern HTML5 API that's widely available).

**Comment by robmyers** [comment]
Yes I used that, it's great and it degrades well on older browsers (I think the only real problem was with iPad).

**Comment by lizadaly** [comment]
Where's the code for the WP plugin so I can see how y'all approached the UI/language?

**Comment by lizadaly** [comment]
I followed CC's recommendations for language and attribution formatting, and added two "copy to clipboard" options—one that copies to plain text, and one that copies including the HTML (and therefore hyperlinks to the deeds).

![image](https://cloud.githubusercontent.com/assets/19571/19282413/4a7822e6-8fbc-11e6-95b5-bb14f9a9bfd5.png)

**Comment by lizadaly** [comment]
Suggestions from Sarah:

* Include a link to the creator page in the attribution if we have it (sometimes we do)
* Hyperlink the license icon everywhere it appears to the correct human-readable deed
* Add text to specify the license version

**Comment by lizadaly** [comment]
These suggestions have been applied where we have the data (like creator URL).
