### ISSUE TITLE
Update PostgreSQL

### ISSUE THREAD

**Issue by pa-w** [creativecommons/open-ledger#230]
Do we want to use PostgreSQL 10?

Let's discuss

**Comment by aldenstpage** [comment]
As we discussed in our meeting, I think it's a good idea. There are some [nice features](https://wiki.postgresql.org/wiki/New_in_postgres_10#Full_Text_Search_support_for_JSON_and_JSONB) related to full text search and JSONB that I think we will eventually find useful.

I'm going to do a dry run migration to PostgreSQL 10 in staging. If it's easy (and it should be), we can move production over early next week.

**Comment by aldenstpage** [comment]
PostgreSQL 10.3 is in production
