### ISSUE TITLE
Update Python in AWS

### ISSUE THREAD

**Issue by pa-w** [creativecommons/open-ledger#231]
3.5?

**Comment by aldenstpage** [comment]
For whatever reason, Python 3.5/6 isn't available in the dropdown menu on the AWS management console. I've tried switching via `eb platform select` without any luck as well. Will have to talk to AWS support.

**Comment by aldenstpage** [comment]
The trick is to make a brand new environment on the correct platform and copy all of the configuration (security groups, environment variables, load balancer settings...) over manually in the AWS console. We're on Python 3.6 in production now.
