### ISSUE TITLE
500px images are returned with watermarks via the API 

### ISSUE THREAD

**Issue by lizadaly** [creativecommons/open-ledger#26]
This wasn't obvious until I started implementing #22 and wanted to include a high-res representation of the image. The non-thumbnail images I get from the 500px API include a watermark:

![image](https://cloud.githubusercontent.com/assets/19571/19167569/3749b580-8bda-11e6-8462-087f0c058410.png)

This is [documented in their API](https://github.com/500px/api-documentation/blob/master/basics/formats_and_terms.md), but I hadn't noticed it when I did my review:

> You'll find the URLs to the image(s) for a photo in the images field in the returned JSON for a photo. The images provided with our standard API access will be watermarked with the 500px logo and attribution. For non-watermarked images please contact sales@500px.com

It might be good to have a conversation with them about next steps.

cc @ryanmerkley

**Comment by janeatcc** [comment]
What would we be wanting from them? Shall we start an email thread vs discussing openly here?

**Comment by lizadaly** [comment]
Took it to email, I'll update this ticket when we have a decision.

**Comment by lizadaly** [comment]
Closing this for now as we work with 500px on next steps.
