### ISSUE TITLE
Add admin privileges to 'liza' IAM account on AWS?

### ISSUE THREAD

**Issue by lizadaly** [creativecommons/open-ledger#33]
I was able to spin up the openledger app successfully in my AWS environment, but the same steps aren't working when I switch to my IAM user in the CC account:

From the Elastic Beanstalk CLI:

```
INFO: Using elasticbeanstalk-us-west-2-194250649014 as Amazon S3 storage bucket for environment data.
ERROR: Service:AmazonCloudFormation, Message:The AWS Access Key Id needs a subscription for the service
ERROR: Failed to launch environment.
```

Ideally, I'd like to not use my own IAM at all, and set up one for the openledger app directly. But I don't have permission:

![image](https://cloud.githubusercontent.com/assets/19571/19319482/0fb359a4-907b-11e6-88f5-9df4b8a588eb.png)

Can my IAM user get upgraded to admin level, so I can create a brand new IAM for the app, and ensure that it has appropriate permissions to spin up an Elastic Beanstalk instance?

**Comment by robmyers** [comment]
Yes let me take a look.

**Comment by robmyers** [comment]
Please try now?

**Comment by lizadaly** [comment]
Now I'm locked out, which may be my fault if my password manager didn't pick up an earlier change. IAM users can't reset their own passwords, so you may need to send a password reset for me? or change it directly and ping me on Slack.

**Comment by lizadaly** [comment]
Sorted! 🎉
