### ISSUE TITLE
DNS entries for openledger on AWS

### ISSUE THREAD

**Issue by lizadaly** [creativecommons/open-ledger#36]
Looks like this is Amazon's recommended path:

http://docs.aws.amazon.com/elasticbeanstalk/latest/dg/customdomains.html

I've deployed and will keep stable:

* openledger-dev.us-west-1.elasticbeanstalk.com 

and presumably will also have:

* openledger.us-west-1.elasticbeanstalk.com 

I feel weird about squatting on openledger.creativecommons.org when this is just a prototype, but then openledger-prototype.creativecommons.org is pretty long. Ideas welcome :)

**Comment by robmyers** [comment]
Feel free to squat, we can swap in the non-prototype version later. cc.org DNS is through cloudflare if you'd like me to point openledger.creativecommons.org somewhere.

**Comment by lizadaly** [comment]
OK, then let's do: 

openledger-dev.creativecommons.org -> openledger-dev.us-west-1.elasticbeanstalk.com 
openledger.creativecommons.org -> openledger-prod.us-west-1.elasticbeanstalk.com

The latter doesn't yet exist but the former does.

**Comment by robmyers** [comment]
I have added those as CNAMEs, they should propagate soon. CloudFlare's CDN is on for them, let me know if that causes any problems and I can turn it off.

**Comment by lizadaly** [comment]
http://openledger-dev.creativecommons.org/ is working just fine, thank you!

**Comment by lizadaly** [comment]
-dev is working fine but openledger.creativecommons.org isn't:

http://openledger.us-west-1.elasticbeanstalk.com/ is up

http://openledger.creativecommons.org/ gives me a Cloudflare DNS resolution error:

![image](https://cloud.githubusercontent.com/assets/19571/19442204/8eebc04c-9456-11e6-8349-82ad3e929e4b.png)

**Comment by robmyers** [comment]
It was aliased to openledger-prod, I've changed it to openledger and it's much happier now.

**Comment by lizadaly** [comment]
Agreed, thank you!
