### ISSUE TITLE
Provide HTTPS on both AWS instances

### ISSUE THREAD

**Issue by lizadaly** [creativecommons/open-ledger#44]
We'll be adding user-facing features soon, including accounts, which means it's a good time to add HTTPS to both hosts:

https://openledger.creativecommons.org/
https://openledger-dev.creativecommons.org/

From some quick reading, it looks like using Let's Encrypt with Elastic Beanstalk is a little tricky. AWS has a free certificate offering now, though: https://us-west-1.console.aws.amazon.com/acm/home?region=us-west-1#/firstrun/

I can probably figure out what buttons to click on if you enable that.

Of course one can also upload a cert from elsewhere too.

Once the certs are in, I'll require the webapp to run under HTTPS only.

**Comment by robmyers** [comment]
"We will send email to the registered owner of each domain listed below. To validate control of the domain, the owner of the domain or an authorized representative must go to the Amazon certificate approval website and approve the request. Further instructions are provided in the body of the email.
 openledger.creativecommons.org
 openledger-dev.creativecommons.org"

I don't suppose you've any mail to admin@, webmaster@ etc. on those hosts set up? If not I'll see if the email to the domain company went through.

**Comment by lizadaly** [comment]
Nope, I haven't done anything but set up web servers on those beanstalk domains that you CNAMEd. And I haven't gotten any mail that seemed to be directed to those addresses.

Sometimes there's an alternate mechanism where you place a small dotfile on the website or similar, which I could do if they offered that.

**Comment by lizadaly** [comment]
What's the next step in getting the certs on the hosts?

**Comment by robmyers** [comment]
The domains aren't showing up in the AWS console so it looks like we have to start again.

I've entered the domains again, if you could please respond again I'll make sure to chase this up.

**Comment by lizadaly** [comment]
Done for both.

**Comment by robmyers** [comment]
Thank you! I've re-approved them, found the resulting certificates where Amazon hid them, and added them to the Elastic Beanstalk instances. They now have https.

**Comment by lizadaly** [comment]
So they do! 🎉 I'll take care of forcing HTTPS-only. Thanks for your help!
