### ISSUE TITLE
Research perceptual hashing work for resource fingerprinting

### ISSUE THREAD

**Issue by lizadaly** [creativecommons/open-ledger#5]
I know there is some prior art that CC has looked at before, but also going to look further afield.

**Comment by robmyers** [comment]
Yes Seneca did some work in this area -

https://github.com/CreativeCommons-Seneca

And Maarten from Kennisland has just had a meeting on the subject of standards for hashing, which would make it easier for us to work with different standards -

http://videorooter.eu/2016/05/21/announcement-workshop-on-standardising-hashing/

**Comment by lizadaly** [comment]
Thanks! It looks like some of that work points back to https://github.com/commonsmachinery/blockhash-python/, which seems very promising.

**Comment by lizadaly** [comment]
https://github.com/JohannesBuchner/imagehash is a candidate, though its dependencies include scikit, which can be tricky to install

**Comment by lizadaly** [comment]
https://github.com/JohannesBuchner/imagehash is the clear winner so far, going to expand the number of tests to push its limits a little.

**Comment by lizadaly** [comment]
I'm happy with imagehash as the approach going forward, but of course may revisit once we try it on lots of data.
