### ISSUE TITLE
Add signup and login 

### ISSUE THREAD

**Issue by lizadaly** [creativecommons/open-ledger#56]
Adding to a List, favoriting, and other personalization behavior requires that the user identify themselves so they can come back. It also allows us to provide the ability to edit/delete personal information.

I'm considering this functionality as applying only to this prototype, but want to surface any issues we'll need to review when an official Open Ledger is available:
- Seek to minimize the amount of personally-identifiable information we collect 
- Make sign up easy (this may be in conflict with the previous, suggests no 'sign up with third party providers')
- Make deletion of personal information irrecovable

I think we need:

**Required**
- an email address (just for password reset, really)
- a password (I'll use the strongest crypto available with Flask)
- a prominent link to the privacy policy (do we need explicit agreement?)

**Optional**
- A "display name", to associate with public user data like lists (would be explicit this does not need to be a real name)

**Other considerations**
- "Delete this account" should destructively delete, not just mark 'deleted', and delete all PII [there's nothing we need to keep]
- If in the future we want people to be able to "claim" works as their own, we will probably need different information if not an outright different account tier and agreement to different terms.

I don't think at this point in the app development we need 2-factor-auth or similar, but open to arguments on all of the above.

**Comment by lizadaly** [comment]
Definitely want @robmyers to weigh in here!

**Comment by robmyers** [comment]
I agree very strongly with the principle of capturing minimal personally identifiable information about users.

If we want a login we are responsible for, with just an email and minimal identifying information, that's an ideal use case for CCID. The Python app would need to accept CAS login from login.creativecommons.org . The blog and the wiki already do this, it hasn't stopped spammers but it has made logging in easier across services.

The advantage to CCID going forward would be that as we add "claim this work", etc., any separate sites or services we implement can use the same sign-on and we can identify users across our services easily that way.

The disadvantages are that it's another moving part to maintain, that it's not always the clearest workflow to be redirected to another site in order to log in, and that it doesn't allow people to log in with existing accounts for convenience. But we can add other authorization backends to RubyCAS (e.g. Google, Facebook, Twitter) if we wish.

**Comment by lizadaly** [comment]
Thanks, do you have some pointers as to where I'd get started on the integration?

**Comment by robmyers** [comment]
Our CAS server is RubyCAS, with an extra theme -

https://github.com/rubycas/rubycas-server

https://github.com/creativecommons/CCID-cas

There's a CAS Flask extension here -

https://github.com/cameronbwhite/Flask-CAS

There is hacky code implementing CAS login via CCID on a small project in -

https://github.com/CreativeCommons-Seneca/qdp

We have CAS integrated with WordPress via -

https://wordpress.org/plugins/cas-maestro/

and MediaWiki via -

https://github.com/creativecommons/CASAuth

**Comment by lizadaly** [comment]
Thanks for the pointer to the Flask integration. I've got it sending auth requests but after successfully authenticating or signing up, it's not redirecting back to the Flask app. Is the CAS provider expecting different parameters, or do you need to whitelist Open Ledger URLs?

The Flask service (on my dev machine) is sending requests to:

https://login.creativecommons.org/?service=http%3A%2F%2Flocalhost%3A5000%2Flogin%2F

But after I auth I just get:

![image](https://cloud.githubusercontent.com/assets/19571/20064032/3f5e0fb2-a4d7-11e6-8d72-0a57f82d4ee0.png)

**Comment by robmyers** [comment]
There needs to be an extra "login" in the path E.g.:

https://login.creativecommons.org/login?service=https%3A%2F%2Fwiki.creativecommons.org%2Findex.php%3Ftitle%3DSpecial%3AUserLogin%26returnto%3DMain_Page

**Comment by lizadaly** [comment]
Thanks, that got me further. Now when it comes back, it tries to validate the request at this URL, which 404s:

https://login.creativecommons.org/cas/serviceValidate?service=http%3A%2F%2Flocalhost%3A5000%2Flogin%2F&ticket=ST-1478548166rMuKJbD64H0jDuRzez1

That's a configurable param on my end (`CAS_VALIDATE_ROUTE`); what's the right URL?

**Comment by lizadaly** [comment]
I found it in the RubyCAS source, so I'm unblocked.

**Comment by lizadaly** [comment]
This is done and working on production. 

The "logout" behavior is a little unsatisfying in that it won't redirect you back to the Open Ledger webapp. Studying RubyCAS suggested that only some versions support this functionality. If you have other implementations that redirect-after-logout I'd be happy to send along the correct parameters, but if no-redirect is the "correct" behavior for other CC properties, then this doesn't need to be change.
