### ISSUE TITLE
Add "delete account" feature to destructively delete all local data

### ISSUE THREAD

**Issue by lizadaly** [creativecommons/open-ledger#68]
There should be a mechanism to delete all user information and user-generated-content from the Open Ledger, which persists some information that it replicates from CAS (maybe more than necessary).

This delete should be destructive.

**Comment by lizadaly** [comment]
@robmyers I implemented this to delete everything user-created in the Open Ledger, but I can't see a way to delete my account from CAS as well. I bet the feature exists but maybe it's just not exposed on https://login.creativecommons.org/login?

**Comment by robmyers** [comment]
I think that:

Deleting the CAS account shouldn't be 1:1 with deleting the user's account in Open Ledger as people may also be using their CAS account to log on to (e.g.) the Wiki.

The user should be offered the ability to delete their CAS acount when they delete their Open Ledger account, with suitable warnings.

That said:

RubyCAS doesn't seem to have a method to delete a user(!). I can't find anything in the spec file or the model, and searching for remove/delete/unregister doesn't show anything.

So I think we'd have to implement that ourselves(!).

I'm hoping I'm wrong about this, but I really can't find anything (I didn't write CCID, Matt did):

https://github.com/creativecommons/CCID-cas

https://github.com/rubycas/rubycas-server

**Comment by lizadaly** [comment]
Oh, I completely agree they should be separate functions; I was just planning on directing the user (with messaging) on where to do the next step if they chose.

**Comment by lizadaly** [comment]
Deployed OL version, but can come back to add messaging or direct URLs to full deletion if we get there.
