### ISSUE TITLE
Add filter on type of license

### ISSUE THREAD

**Issue by lizadaly** [creativecommons/open-ledger#7]
We'll upgrade this to be more user-friendly, but start with just simple filtering on license name.

**Comment by lizadaly** [comment]
Note that a very literal implementation of this will mean that a search for CC-BY will not return anything from Rijksmuseum or Wikimedia, as those are CC0 only.

**Comment by janeatcc** [comment]
Here are the guidelines we provide platforms: https://creativecommons.org/platform/toolkit/#enabling-cc-search-and-discovery

We prefer by category of reuse (eg. stuff I can remix commercially, versus license).

**Comment by lizadaly** [comment]
OK, I updated the prototype to include the two recommended categories from the guidelines. 

You can also request specific licenses if you edit the URL (see the "sheep" option in the "Searches to try" list). We could bury that in an "advanced search" option.

```
LICENSE_GROUPS = {
    # All open licenses
    "ALL": ('BY', 'BY-NC', 'BY-ND', 'BY-SA', 'BY-NC-ND', 'BY-NC-SA', 'PDM', 'CC0'),
    # All CC licenses
    "ALL-CC": ('BY', 'BY-NC', 'BY-ND', 'BY-SA', 'BY-NC-ND', 'BY-NC-SA'),
    # All licenses allowing commercial use
    "ALL-$": ('BY', 'BY-SA', 'BY-ND', 'CC0', 'PDM'),
    # All licenses allowing modifications
    "ALL-MOD": ('BY', 'BY-SA', 'BY-NC', 'BY-NC-SA', 'CC0', 'PDM'),
}
```

I defined the above as special groups of licenses we may want to treat as a unit. Let me know if you can think of other categories that would be useful.

**Comment by janeatcc** [comment]
These filters look good to me for now, though the actual search returning them seems broken, but I'm sure you're working on that!

**Comment by lizadaly** [comment]
A search for "sunset" with "Use for commercial purposes" and "Modify, adapt, or build upon" both checked should not return NC or ND results.

**Comment by lizadaly** [comment]
I believe this should be fixed.
