### ISSUE TITLE
Add Google Analytics

### ISSUE THREAD

**Issue by lizadaly** [creativecommons/open-ledger#86]
It might be nice to put this in the CC GA account but under a separate site so it's easier to report on, but that's up to you guys.

What's the GA code I should use?

**Comment by robmyers** [comment]
See email for code for live. Do we need one for staging as well?

**Comment by lizadaly** [comment]
Nah.

**Comment by robmyers** [comment]
OK. :-)

**Comment by lizadaly** [comment]
Deployed live.
