### ISSUE TITLE
Add performance analytics

### ISSUE THREAD

**Issue by lizadaly** [creativecommons/open-ledger#87]
I like New Relic, though its free tier is becoming increasingly underpowered. Does CC use NR, and if not, would you like to?  

Ideally sign up/use their non-profit tier, which is much more full-featured than the free tier: https://newrelic.com/nonprofit

**Comment by lizadaly** [comment]
NR also doubles as a uptime notifier, which we should also monitor.

**Comment by robmyers** [comment]
We do use New Relic. I just need to recover the password. Do you need access to the account or is this something I should do?

**Comment by lizadaly** [comment]
I need access, so I can see what's wrong when it tells me something's wrong.

**Comment by robmyers** [comment]
OK, see email. :-)

**Comment by lizadaly** [comment]
New Relic is now sending data for the Open Ledger app:

![image](https://cloud.githubusercontent.com/assets/19571/21161902/a85eafd8-c158-11e6-815e-b1934800fa71.png)
