### ISSUE TITLE
Add waiting indicator while image grid loads and lays out

### ISSUE THREAD

**Issue by eoinnoble** [creativecommons/open-ledger#92]
When you first type in a new query and hit ENTER it takes a long time for the results to load, maybe because there are no concurrent downloads? Adding some kind of loading GIF would be a good temporary measure, but longer term some kind of lazyloading would probably be a good idea, as well as fetching the right size of image so no resizing/repainting is required by the browser.

**Comment by lizadaly** [comment]
Agreed, I've wanted to put a loading spinner. (What's actually happening is that it's waiting for all the images to load, so it can nicely lay out the grid and remove images that don't load. The effect is even more pronounced if your internet connection is slow.)

**Comment by lizadaly** [comment]
Added. Will also use New Relic to dive into potential optimizations on the search end.
