### ISSUE TITLE
CC license icons don't need underlining

### ISSUE THREAD

**Issue by eoinnoble** [creativecommons/open-ledger#93]
If you go to a photo page and hover over the CC icons you'll see a small line appear behind them. The `a` element for the CC license icons shouldn’t have `text-decoration: underline` on `:hover`.

![screen shot 2016-12-12 at 13 27 14](https://cloud.githubusercontent.com/assets/3576438/21100986/c3865d28-c06e-11e6-9090-2db732261fb9.png)

**Comment by lizadaly** [comment]
Fixed
