### ISSUE TITLE
Shouldn't be able to remove items from the 'Favourites' list

### ISSUE THREAD

**Issue by eoinnoble** [creativecommons/open-ledger#96]
Items in the 'Favourites' list shouldn't display a 'Remove from list' icon, the 'De-favourite' icon should be sufficient. There's no world in which a user would want an item removed from that list and the 'Favourites' icon still highlighted on the individual photo page.

**Comment by lizadaly** [comment]
Agreed, this is how it should work. Will do.

**Comment by lizadaly** [comment]
This has been reimplemented to make the Favorites "list" draw directly from the current set of favorited items, rather than being a mirror copy.
